//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAssistantBot.Dialogs.Tar.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TarStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TarStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartAssistantBot.Dialogs.Tar.Resources.TarStrings", typeof(TarStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to notify your team?.
        /// </summary>
        public static string ASK_TO_SEND_NOTES_TO_TEAM {
            get {
                return ResourceManager.GetString("ASK_TO_SEND_NOTES_TO_TEAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok. I submitted your sick day to TAR.
        /// </summary>
        public static string CONFIRM_SICK_DAY_SUBMITTED {
            get {
                return ResourceManager.GetString("CONFIRM_SICK_DAY_SUBMITTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry to hear that. I hope you feel better soon.
        /// </summary>
        public static string FEEL_BETTER_SOON {
            get {
                return ResourceManager.GetString("FEEL_BETTER_SOON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok. I cancelled your meetings today..
        /// </summary>
        public static string MEETING_CANCELLED {
            get {
                return ResourceManager.GetString("MEETING_CANCELLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok. I notified your team.
        /// </summary>
        public static string SENT_NOTES_TO_TEAM {
            get {
                return ResourceManager.GetString("SENT_NOTES_TO_TEAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take care.
        /// </summary>
        public static string TAKE_CARE {
            get {
                return ResourceManager.GetString("TAKE_CARE", resourceCulture);
            }
        }
    }
}
