//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAssistantBot.Dialogs.Immigration.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ImmigrationStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ImmigrationStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartAssistantBot.Dialogs.Immigration.Resources.ImmigrationStrings", typeof(ImmigrationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no travel advisories for india as of today!.
        /// </summary>
        public static string ACTION_PROMPT {
            get {
                return ResourceManager.GetString("ACTION_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please send an email to Askusi8@microsoft.com​​​​ , Have a Safe Journey!!.
        /// </summary>
        public static string HAVE_ATTORNEY {
            get {
                return ResourceManager.GetString("HAVE_ATTORNEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I checked your visa status and looks like you have a valid L-1 visa with which you can use to travel outside US! 
        ///Please carry the below documents to ensure better Immigration clearance experience:
        ///•	Latest Passport 
        ///•	Signed I-129
        ///•	If you are traveling with your dependents please carry your marriage certificate..
        /// </summary>
        public static string HAVE_NONUS {
            get {
                return ResourceManager.GetString("HAVE_NONUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like you have EAD/AP case is filed with USCIS and during this time if you travel outside United States then your EAD/AP will get rejected. If you have more question feel free to submit Ask US Immigration ticket here. Do you want to connect with your legal attorney ?.
        /// </summary>
        public static string HAVE_OUTSIDEUS_PENDING {
            get {
                return ResourceManager.GetString("HAVE_OUTSIDEUS_PENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are free to travel anywhere within {0}!.
        /// </summary>
        public static string HAVE_US {
            get {
                return ResourceManager.GetString("HAVE_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you need your Attorney Information ?.
        /// </summary>
        public static string LEGAL_PROMPT {
            get {
                return ResourceManager.GetString("LEGAL_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you planning to travel outside united states or within united States?.
        /// </summary>
        public static string TRAVEL_PROMPT {
            get {
                return ResourceManager.GetString("TRAVEL_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have a safe Journey!.
        /// </summary>
        public static string TRAVEL_SAFE {
            get {
                return ResourceManager.GetString("TRAVEL_SAFE", resourceCulture);
            }
        }
    }
}
